server:
  port:8089
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect:
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest
  application:
    name: email-service


